### ISSUE TITLE
Broken after upgrade 2025/5

### ISSUE THREAD

**Issue by starwars1999** [jovana/remko-heat-pump#9]
Hi,
after the upgrade to 2025.5 I only got this error when starting homeassistant:

> Logger: homeassistant.setup
> Quelle: setup.py:426
> Erstmals aufgetreten: 14. Mai 2025 um 07:52:36 (1 Vorkommnis)
> Zuletzt protokolliert: 14. Mai 2025 um 07:52:36
> 
> Error during setup of component remko_heatpump: 'HomeAssistant' object has no attribute 'helpers'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 426, in _async_setup_component
>     result = await task
>              ^^^^^^^^^^
>   File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/remko_heatpump/__init__.py", line 25, in setup
>     hass.helpers.discovery.load_platform('sensor', DOMAIN, {}, config)
>     ^^^^^^^^^^^^
> AttributeError: 'HomeAssistant' object has no attribute 'helpers'

Any idea, how to solve this error?

**Comment by starwars1999** [comment]
Ok, I found it. you have to add and change one line in \__init\__.py:
add this line at the beginning:
>from homeassistant.helpers.discovery import async_load_platform

change the old hass.helpers-line to this one:
>    hass.loop.call_soon_threadsafe(hass.async_create_task, async_load_platform(hass, 'sensor', DOMAIN, {}, config))
>
>    return True

after a restart of ha the warnings are gone and all sensor values appear again

**Comment by jovana** [comment]
> Ok, I found it. you have to add and change one line in __init__.py: add this line at the beginning:
> 
> > from homeassistant.helpers.discovery import async_load_platform
> 
> change the old hass.helpers-line to this one:
> 
> > hass.loop.call_soon_threadsafe(hass.async_create_task, async_load_platform(hass, 'sensor', DOMAIN, {}, config))
> > return True
> 
> after a restart of ha the warnings are gone and all sensor values appear again

Thanks for sharing this fix. I'm not running the latest HA. I will update the code after the update.

**Comment by jovana** [comment]
I have modify the code, and now testen en working on version: 2025.8.2
