### ISSUE TITLE
Not working after HA Core Update 2025/1

### ISSUE THREAD

**Issue by jroegner** [jovana/remko-heat-pump#7]
Since HA Core Update 2025/1 the integration doesn't anymore:

_Logger: homeassistant.setup
Quelle: setup.py:497
Erstmals aufgetreten: 11:10:48 (1 Vorkommnisse)
Zuletzt protokolliert: 11:10:48

Unable to prepare setup for platform 'remko_heatpump.sensor': Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py))._

**Comment by jroegner** [comment]
Found a solution. In sensor.py you must change

`from homeassistant.const import TEMP_CELSIUS, POWER_KILO_WATT, POWER_WATT`
to
`from homeassistant.const import UnitOfTemperature, UnitOfPower`

and of course also the value of the unit return for each sensor

**Comment by Dragancokan** [comment]
What exactly do you mean by: and of course also the value of the unit return for each sensor?

**Comment by jroegner** [comment]
For sensors with unit temperature:
from:
```
@ property
    def unit_of_measurement(self) -> str:
        """Return the unit of measurement."""
        return TEMP_CELSIUS
```
to:
```
@ property
    def unit_of_measurement(self) -> str:
        """Return the unit of measurement."""
        return UnitOfTemperature.CELSIUS
```

For sensors with unit power
from:
```
@ property
    def unit_of_measurement(self) -> str:
        """Return the unit of measurement."""
        return POWER_WATT
```
to:
```
@ property
    def unit_of_measurement(self) -> str:
        """Return the unit of measurement."""
        return UnitOfPower.WATT
```

**Comment by jovana** [comment]
Update the code it should work on HA verion: 2025.8.2 now.
